"""
Ports (Protocol) — application phụ thuộc interface, không phụ thuộc Mongo/YOLO/HTTP.
Infrastructure / tests implement các Protocol này.
"""
from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional, Protocol, Sequence, Set

from domain.reset_policy import ResetResult


class CameraConfigRepository(Protocol):
    async def get_all(self) -> List[Dict[str, Any]]: ...
    async def get_by_area(self, area: str) -> List[Dict[str, Any]]: ...
    async def create(self, doc: Dict[str, Any]) -> str: ...
    async def update_by_camera_id(self, camera_id: int, data: Dict[str, Any]) -> bool: ...
    async def delete_by_camera_id(self, camera_id: int) -> bool: ...


class PairsRepositoryPort(Protocol):
    async def get_by_zone(self, zone_id: str) -> List[Dict[str, Any]]: ...
    async def set_enabled(
        self, start_point: str, end_point: Optional[str], enabled: bool
    ) -> bool: ...
    async def create(self, doc: Dict[str, Any]) -> str: ...
    async def delete(self, start_point: str, end_point: Optional[str]) -> bool: ...
    async def get_as_tuples(self) -> List: ...


class NodeRepositoryPort(Protocol):
    async def get_by_zone(self, zone_id: str) -> List[Dict[str, Any]]: ...
    async def get_by_id(self, node_id: str) -> Optional[Dict[str, Any]]: ...
    async def get_by_camera(self, camera_id: int) -> List[Dict[str, Any]]: ...
    async def set_enabled(self, node_id: str, enabled: bool) -> bool: ...
    async def set_camera_nodes_enabled(self, camera_id: int, enabled: bool) -> int: ...
    async def update_priority(self, node_id: str, priority: int) -> bool: ...
    async def create(self, doc: Dict[str, Any]) -> str: ...
    async def delete_by_node_id(self, node_id: str) -> bool: ...


class CameraRuntime(Protocol):
    def is_ready(self) -> bool: ...
    def start_all(self) -> None: ...
    def stop_all(self) -> None: ...
    def set_zone_enabled(self, zone: str, on: bool) -> None: ...
    def get_status(self) -> Dict[str, Any]: ...
    def get_preview_jpeg(self, camera_id: int, detect: bool): ...
    def get_preview_meta(self, camera_id: int): ...
    def get_rtsp_url(self, camera_id: int): ...


class InferencePort(Protocol):
    def is_ready(self) -> bool: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def is_paused(self) -> Optional[bool]: ...
    def is_model_loaded(self) -> bool: ...
    def wait_model_ready(self, timeout: float) -> bool: ...
    def load_error(self) -> Optional[str]: ...


class NodeStateStore(Protocol):
    def is_ready(self) -> bool: ...
    def update_detection(self, node_id: str, detected: bool) -> None: ...
    def has_node(self, node_id: str) -> bool: ...
    def toggle_flag(self, node_id: str) -> Optional[bool]: ...
    def discard_from_ready(self, node_id: str) -> None: ...
    def get_detected_start_nodes(self) -> Set[str]: ...
    def snapshot_points(self) -> Dict[str, Dict[str, bool]]: ...
    def apply_reset(self, order_id: str, status: int) -> ResetResult: ...
    def ready_starts(self) -> Set[str]: ...
    def ready_ends(self) -> Set[str]: ...
    def get_validate_pairs(self) -> Sequence: ...
    def set_pair_used(
        self, start_point: str, end_point: str, order_id: str, empty_car: bool = False
    ) -> None: ...
    def process_starts(self) -> None: ...
    def process_ends(self) -> None: ...


class DispatchGateway(Protocol):
    """Gửi payload ICS. Retry nằm trong HttpDispatchGateway."""
    def send(self, payload: Dict[str, Any]) -> bool: ...


class RuntimeControl(Protocol):
    async def start(self) -> Dict[str, Any]: ...
    def stop(self) -> Dict[str, Any]: ...
    def status(self) -> Dict[str, Any]: ...
    async def reload(self) -> Dict[str, Any]: ...


class DbHealthPort(Protocol):
    """Ping database — dùng cho /health."""
    async def ping(self) -> bool: ...


class WebrtcRunnerPort(Protocol):
    """Trạng thái MediaMTX process + watchdog."""
    def status(self) -> Dict[str, Any]: ...


class UserRepositoryPort(Protocol):
    async def get_by_username(self, username: str) -> Optional[Dict[str, Any]]: ...
    async def get_by_id(self, user_id: str) -> Optional[Dict[str, Any]]: ...


class RefreshTokenStore(Protocol):
    """
    Lưu refresh token đã hash — không lưu bản thô.

    Single session: `save` xoá phiên cũ của user, nên đăng nhập máy mới đẩy
    máy cũ ra.
    """
    async def save(self, user_id: str, token_hash: str, expires_at: datetime) -> None: ...
    async def find(self, token_hash: str) -> Optional[Dict[str, Any]]: ...
    async def revoke_user(self, user_id: str) -> None: ...


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, hashed: str) -> bool: ...
    def dummy_hash(self) -> str:
        """Hash giả để verify vẫn chạy khi username không tồn tại (chống dò user)."""
        ...


class TokenIssuer(Protocol):
    """Phát access token (JWT) + refresh token (chuỗi ngẫu nhiên)."""
    def issue_access(self, user: Dict[str, Any]) -> Dict[str, Any]: ...
    def decode_access(self, token: str) -> Optional[Dict[str, Any]]: ...
    def new_refresh(self) -> Dict[str, Any]: ...
    def hash_refresh(self, raw: str) -> str: ...


class AuthAuditPort(Protocol):
    """Ghi sự kiện đăng nhập + đếm số lần sai để chặn dò mật khẩu."""
    async def log_event(
        self, username: str, event: str, ip: str, user_agent: str = ""
    ) -> None: ...
    async def count_recent_failures(self, username: str, minutes: int) -> int: ...


class FrameProvider(Protocol):
    """
    Cung cấp frame + metadata mới nhất cho snapshot.
    
    CameraManager implement, inject vào SnapshotFsStore.
    """
    def capture_for_node(self, node_id: str) -> Optional[Dict[str, Any]]:
        """
        Lấy frame + detection mới nhất cho node.
        
        Returns dict:
            {
                "frame": torch.Tensor (CUDA),
                "event": torch.cuda.Event hoặc None,
                "detections": torch.Tensor hoặc None,
                "rois": list,
                "detection_ts": float,
                "cam_id": str
            }
        hoặc None nếu node không tìm thấy hoặc camera chưa có frame.
        """
        ...
