"""
Ports (Protocol) — application phụ thuộc interface, không phụ thuộc Mongo/YOLO/HTTP.
Infrastructure / tests implement các Protocol này.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol, Sequence, Set

from domain.reset_policy import ResetResult


class CameraConfigRepository(Protocol):
    async def get_all(self) -> List[Dict[str, Any]]: ...
    async def get_by_area(self, area: str) -> List[Dict[str, Any]]: ...
    async def create(self, doc: Dict[str, Any]) -> str: ...
    async def update_by_camera_id(self, camera_id: int, data: Dict[str, Any]) -> bool: ...
    async def delete_by_camera_id(self, camera_id: int) -> bool: ...


class PairsRepositoryPort(Protocol):
    async def get_by_zone(self, zone_id: str) -> List[Dict[str, Any]]: ...
    async def set_enabled(
        self, start_point: str, end_point: Optional[str], enabled: bool
    ) -> bool: ...
    async def create(self, doc: Dict[str, Any]) -> str: ...
    async def delete(self, start_point: str, end_point: Optional[str]) -> bool: ...
    async def get_as_tuples(self) -> List: ...


class NodeRepositoryPort(Protocol):
    async def get_by_zone(self, zone_id: str) -> List[Dict[str, Any]]: ...
    async def get_by_id(self, node_id: str) -> Optional[Dict[str, Any]]: ...
    async def get_by_camera(self, camera_id: int) -> List[Dict[str, Any]]: ...
    async def set_enabled(self, node_id: str, enabled: bool) -> bool: ...
    async def set_camera_nodes_enabled(self, camera_id: int, enabled: bool) -> int: ...
    async def update_priority(self, node_id: str, priority: int) -> bool: ...
    async def create(self, doc: Dict[str, Any]) -> str: ...
    async def delete_by_node_id(self, node_id: str) -> bool: ...


class CameraRuntime(Protocol):
    def is_ready(self) -> bool: ...
    def start_all(self) -> None: ...
    def stop_all(self) -> None: ...
    def set_zone_enabled(self, zone: str, on: bool) -> None: ...
    def get_status(self) -> Dict[str, Any]: ...


class InferencePort(Protocol):
    def is_ready(self) -> bool: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def is_paused(self) -> Optional[bool]: ...
    def is_model_loaded(self) -> bool: ...
    def wait_model_ready(self, timeout: float) -> bool: ...
    def load_error(self) -> Optional[str]: ...


class NodeStateStore(Protocol):
    def is_ready(self) -> bool: ...
    def update_detection(self, node_id: str, detected: bool) -> None: ...
    def has_node(self, node_id: str) -> bool: ...
    def toggle_flag(self, node_id: str) -> Optional[bool]: ...
    def discard_from_ready(self, node_id: str) -> None: ...
    def get_detected_start_nodes(self) -> Set[str]: ...
    def snapshot_points(self) -> Dict[str, Dict[str, bool]]: ...
    def apply_reset(self, order_id: str, status: int) -> ResetResult: ...
    def ready_starts(self) -> Set[str]: ...
    def ready_ends(self) -> Set[str]: ...
    def get_validate_pairs(self) -> Sequence: ...
    def set_pair_used(
        self, start_point: str, end_point: str, order_id: str, empty_car: bool = False
    ) -> None: ...
    def process_starts(self) -> None: ...
    def process_ends(self) -> None: ...


class DispatchGateway(Protocol):
    """Gửi payload ICS. Retry nằm trong HttpDispatchGateway."""
    def send(self, payload: Dict[str, Any]) -> bool: ...


class RuntimeControl(Protocol):
    async def start(self) -> Dict[str, Any]: ...
    def stop(self) -> Dict[str, Any]: ...
    def status(self) -> Dict[str, Any]: ...
    async def reload(self) -> Dict[str, Any]: ...


class ZonePairsLookup(Protocol):
    def get_pairs(self, zone: str) -> List: ...
